### PR TITLE
fix brazilian translation filename

### PR DESCRIPTION
**Pull request by a-detiste**
this was caught while packaging for Debian

### CODE REVIEW

**Comment by adrienverge** [comment]
Hello Alexandre, thanks for contributing and fixing this! Can you just explain (inside the commit message) why this rename is useful/necessary? It's not obvious to me.

**Comment by a-detiste** [comment]
It is necessary that the filename exactly matches the case-sensitive locale as defined in the environment, otherwise it is never picked up. This glitch was found by the lintian Debian linter. I did not took any action to fix this in last Debian upload and hope this fix will be included in a next release.

You can set your computer to Brasilian if you want to do an end-to-end check. (or just overriding LC_*-something in a shell with "export")

**Comment by adrienverge** [comment]
OK! Again, can you just state it inside the commit message? Then it will be good to go :+1:

**Comment by a-detiste** [comment]
done

**Review by adrienverge — APPROVED** [review]
Thanks!

**Comment by a-detiste** [comment]
The metadata _inside_ the file was already correct.

pt_BR.po:"Language-Team: \n"
pt_BR.po:"Language: pt_BR\n"

**Pull request merged**
