### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by macagua**
- Added Spanish translation

### CODE REVIEW

**Comment by macagua** [comment]
@adrienverge please can check this and merge it? Thanks!

**Comment by andreynovikov95** [comment]
@adrienverge, I update the language line in README.rst in #74

**Comment by adrienverge** [comment]
It was integrated in https://github.com/adrienverge/PhotoCollage/pull/74, thanks to @andreynovikov95. Thanks for contributing!

**Comment by macagua** [comment]
Thanks guys! :+1:

**Pull request closed without merging**
