### PR TITLE
 App icon is missing from the Linux Mint menu #100

### PR DESCRIPTION
**Pull request by ChrisLauinger77**

### CODE REVIEW

**Comment by adrienverge** [comment]
Hello Christian, thanks for contributing, but as you might expect, this PR is not acceptable: it changes a scalable vectorial SVG into a SVG that contains a fixed-pixel PNG image.

**Comment by ChrisLauinger77** [comment]
Really ? I converted the png to svg using InkScape.

**Comment by adrienverge** [comment]
> Really ?

Yes. You can open the SVG file as text to see this. Or just zoom into your image: it's not vectorial.
Capture d’écran du 2024-06-11 08-06-20

**Comment by ChrisLauinger77** [comment]
Intresting - thx for pointing that out. I check the settings in InkScape - might be some thing I can do better in the future

**Pull request closed without merging**
