### PR TITLE
Drop support for EOL Python 2.7-3.4

### PR DESCRIPTION
**Pull request by hugovk**
Same as #67 but also drops support for EOL versions.

* https://devguide.python.org/#status-of-python-branches
* https://devguide.python.org/devcycle/#end-of-life-branches

### CODE REVIEW

**Comment by adrienverge** [comment]
I know Python 2 was recently sunset, but I don't see the need to drop support now, if it still continues to work. Is the code simplification it brings the only reason, or do you have another one?

**Comment by hugovk** [comment]
Yeah, you can keep it if you like, maybe not as big benefits for this project as for others.

Here's some reasons:

* Security: 
  * Python 2.7 is no longer maintained and won't have any new security vulnerabilities fixed
  * Pillow no longer supports Python 2.7, and the last release for 2.7 doesn't have [security fixes](https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#security)
  * PyCairo no longer supports Python 2.7
* You can start to use new Python features without worrying about old versions
* Use fewer CI testing resources
* It's becoming less and less used or relevant: https://github.com/hugovk/pypi-tools/blob/master/README.md#examples

**Comment by adrienverge** [comment]
OK, you convinced me. Can you please rebase on latest master?

**Comment by hugovk** [comment]
Rebased!

**Pull request merged**
